# Generated by Django 2.2 on 2023-06-04 11:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('city_name', models.CharField(max_length=30)),
                ('tech_skills', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'Python'), ('java', 'Java'), ('ruby', 'Ruby'), ('docker', 'Docker'), ('node', 'Node'), ('js', 'JS')], max_length=6)),
            ],
        ),
    ]
